import turtle
wn = turtle.Screen()
jim = turtle.Turtle()
jim.pensize(10)
jim.color("blue")
jim.penup()
jim.goto(-110, -25)
jim.pendown()
jim.circle(45)
jim.color("black")
jim.penup()
jim.goto(0, -25)
jim.pendown()
jim.circle(45)
jim.color("red")
jim.penup()
jim.goto(110, -25)
jim.pendown()
jim.circle(45)
jim.color("yellow")
jim.penup()
jim.goto(-55, -75)
jim.pendown()
jim.circle(45)
jim.color("green")
jim.penup()
jim.goto(55, -75)
jim.pendown()
jim.circle(45)
